streamlite-vertical-slider 2.5.5
AnacondaRecipes/streamlit-vertical-slider-feedstock pull request #2
Opened 2024-04-09 17:58 UTC by psteyer

{package} {version} {:snowflake:}

**Destination channel:** {Snowflake | defaults}

### Links

- [{ticket_number}]() 
- [Upstream repository]()
- [Upstream changelog/diff]()
- Relevant dependency PRs:
  - ...

### Explanation of changes:

- ...

2024-04-10 18:30 UTC, anaconda-pkg-build commented
<details><summary>Linter check found the following problems:</summary>
ERROR conda.cli.main_run:execute(124): `conda run conda-lint /tmp/abs_e2rg4a0j4e/clone` failed. (See above for error)
The following problems have been found:

===== ERRORS =====
- clone/recipe/meta.yaml:1: patch_must_be_in_build: patch must be in build when source/patches is set.
===== Final Report: =====
1 Error and 0 Warnings were found

</details>

2024-04-11 16:45 UTC, lorepirri requested changes
The destination channel is **Default**!

2024-04-11 18:27 UTC, lorepirri approved these changes
LGTM! Good job with adding the patches!

2024-04-11 18:56 UTC, ViridianMelody approved these changes

2024-04-11 21:35 UTC, merged